### ISSUE TITLE
Questions about the multiple testing correction

### ISSUE THREAD

**Issue by SWei2333** [nclark-lab/RERconverge#102]
Dear professer,

I have two questions:

(1) I performed a binary analysis(correlateWithBinaryPhenotype) on my data, and after adjustment, none of the p.adj values were below 0.05. Should I automatically switch to a different multiple testing correction method and reanalyze, or can I trust the results of the significant p-values?

(2) I found that the results showing conserved evolutionary rates align better with my expectations. However, since my p-values could not pass FDR correction, I am not entirely confident in the reliability of the current results. Could you suggest any additional analyses I could perform to demonstrate the existence of purifying selection? I have attempted to identify genes with dN/dS < 1 using PAML and K > 1 using HyPhy-RELAX, but their overlap with RERconverge results is not ideal.

Thank you for your help, I'm looking forward to your reply!

Best wishes

**Comment by nclark-lab** [comment]
Hello, I'd suggest two things. The p.adj values are from a Benjamini-Hochberg correction, but you could try another FDR measure. Also, it can be justified to examine genes at a slightly higher FDR, just remembering that the false discovery is higher.
Last, even when individual genes do not pass a significance threshold, the ranking of genes (the top genes out of the whole list) is still informative. Any functional categories that are overrepresented are still a non-random distribution of functional annotations after ranking the genes by RERconverge. So, functional enrichment analysis is still valid.
For example, in our initial studies of subterranean mammals few genes passed corrections on their own, but the ranked list was clearly highly enriched for visual perception genes. I hope this helps.
