### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by yuzhenpeng** [nclark-lab/RERconverge#23]
I'm sorry to bother you, but I have the following error information during installation

install_github("nclark-lab/RERconverge")
Downloading GitHub repo nclark-lab/RERconverge@master
from URL https://api.github.com/repos/nclark-lab/RERconverge/zipball/master

Installation failed: transfer closed with outstanding read data remaining

**Comment by mchikina** [comment]
I have never seen this error before. Have you gotten it more than once?

**Comment by yuzhenpeng** [comment]
I used RStudio, and I tried it many times, but failed

The current error information is as follows:

Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
Timeout was reached: Connection timed out after 10000 milliseconds

Is this due to proxy/firewall?

**Comment by yuzhenpeng** [comment]
It's really fun. I got it manually. 

I think it's probably because of the Github firewall that it can't be installed properly.

But now there seems to be a new problem：

> plotRers(mamRERlogWs,"BEND3",phenv=phenvExample)
Error in data.frame(species = names(e1plot), rer = e1plot, stringsAsFactors = FALSE) %>%  : 
  could not find function "%>%"

I'll try it myself first and then discuss it with you.

**Comment by sorrywm** [comment]
The selectforegroundbranches function is something we are working on but is not currently part of the package. We'll have an updated vignette soon that addresses this.

The plotRers error is one we have seen before and are troubleshooting. We'll let you know when we've fixed it in the master branch. In the mean time, if you'd like to source plottingFuncs.R from the UpdateVignette branch, the plotRers function should work.

These steps are not strictly necessary for running the analyses later in the workflow, so you can try to continue with that if you'd like.

**Comment by yuzhenpeng** [comment]
I really appreciate your help.

**Comment by Amylith** [comment]
I believe the error in plotRers is fixed on the master branch, so you can reinstall the package and try working through that part of the walkthrough again.

**Comment by yuzhenpeng** [comment]
When I used my own data analysis, I had the following problems, and I didn't know how to handle them.

> mamRERlogW=getAllResiduals(mamTrees,useSpecies=mamTrees$masterTree$tip.label,transform = "sqrt", weighted = T, scale = T,cutoff = 0.001)

**Comment by nclark-lab** [comment]
New plotting functions are working and described in the walkthrough (vignette).
