### ISSUE TITLE
Revise plotRers to fix issue with duplicated factor level

### ISSUE THREAD

**Issue by sorrywm** [nclark-lab/RERconverge#24]
As user yuzhenpeng pointed out, the version of plotRers that installs from the master branch yields the following error:

plotRers(mamRERlogWs,"BEND3",phenv=phenvExample)
Error in levels<-(*tmp*, value = as.character(levels)) :
factor level [53] is duplicated

This may be an issue with setting the factors for the y-axis in ggplot (line 469).

**Comment by Amylith** [comment]
Fixed and added to master branch - I added unique() to levels given to ggplots to remove duplicate names
