### ISSUE TITLE
Trouble calculating RER by getAllResiduals, NaN generated when read trees

### ISSUE THREAD

**Issue by lmcai** [nclark-lab/RERconverge#35]
Hi,
I had an error message trying to use the getAllResiduals function. I followed the instructions in the walk through (https://www.csb.pitt.edu/faculty/clark/files/RERconvergeAnalysisFullWalkthrough.html).

#load the library and read in trees
library(RERconverge)
treefile=readTrees('RERconverge_input.tree')
RERw=getAllResiduals(treefile,transform = 'sqrt',weighted = T,scale=T)

Then I get the following error:
error: Mat::elem(): index out of bounds
Error in fastLmResidMat(data, mod) : Mat::elem(): index out of bounds

When I check the treefile, I found the majority of treefile$length is NaN. I guess this might be the problem here? Is this due to missing root species or something?

I am also attaching my input file here in case it helps.
[RERconverge_input.tree.zip](https://github.com/nclark-lab/RERconverge/files/2641412/RERconverge_input.tree.zip)

Best,
Liming

**Comment by sorrywm** [comment]
Hi Liming,

Thank you for being in touch! I think there may be an issue with the format of your trees. readTrees makes a master tree from combining data for all gene trees that have all species present. In your trees, there is a branch length missing for all of these all-species trees, so the length of this branch cannot be estimated for the master tree. This creates problems down the line. Here is an example of one of your trees, with the missing branch length indicated by a question mark (?):
OG0000092       ((((Cit:0.27783618230683654,Ath:0.7015177326840584):0.015170031455602964,((((Jat:0.07700236916648931,Mes:0.1107066837750705):0.033874745500726035,Sap:0.6667235355930785):1.64448593606487E-6,Ptr:0.15322726541799572):0.05790599490280063,((Pru:0.17895307842993233,Cuc:0.427003471316044):1.64448593606487E-6,Gly:0.4180708281688211):0.020528167357532625):0.006293737879377798):0.0491953479133243,((Hel:0.4709436777580748,Dau:0.2823034741872248):0.043597446947399046,((((Han:0.1118017797968531,Ses:0.11517234960750651):0.022875182364620782,((Str:0.4336094826815396,Pht:0.13967244060661657):0.046136837912908006,Mim:0.36842045602122175):0.07684611017476849):0.06293837866594326,Ole:0.24088990397496715):0.0622745453619488,((((Sol:0.05157527494534048,Cap:0.05836242738349988):0.03278204652886242,Nic:0.06456957603549592):0.10462997430433033,(Ipo:0.16355631903228676,Cus:0.4621635976531882):0.1797485760612706):0.08157327923248744,Cof:0.15828163955692284):0.018749661978631888):0.05492091075378827):0.09403288647190472)**:?**,Vvi:0.21198040453330128);

I believe if you provide edge lengths for this branch for all genes that have all species present, this should resolve your issue; however, if you continue to run into errors, please let us know.

Thank you for trying out our software!

Wynn

**Comment by lmcai** [comment]
Hi Wynn,
You are absolutely right! I used some artificial numbers and it worked! Thank you so much for your help!
Best,
Liming
