### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by vanzod** [nclark-lab/RERconverge#36]
We would like to provide `RERconverge` in our cluster software stack since some of our users requested it. However to do so we would need you to create releases whenever the software is updated. Is there any chance this can be done?

Thank you

**Comment by wgmao** [comment]
Thanks for your feedback. We have just released the first version of RERconverge and we will keep creating releases once the package is updated. Let us know if you have any problems when installing the package.

**Comment by vanzod** [comment]
Thanks a lot for following up so quickly on my request.
