### ISSUE TITLE
data directory does not contain trees

### ISSUE THREAD

**Issue by vanzod** [nclark-lab/RERconverge#37]
Athough the installation of `RERconverge` completes successfully by building it from the archive in the 0.1.0 release with `R CMD INSTALL v0.1.0.tar.gz`, the `/data` directory does not contain the correct tree files:
```
$ ls RERconverge/data
Rdata.rdb  Rdata.rds  Rdata.rdx
```
Can you please advise?

**Comment by wgmao** [comment]
The tree files are under the directory RERconverge/extdata. We also provide tree files for mammals, Drosophila, and yeast via https://bit.ly/2J2QBnj.

**Comment by vanzod** [comment]
@wgmao Please apologize my total ignorance in the specific topic. What I meant is that the content of `/data` after installing does not match the content of `/data` in the repo. Hence users cannot run the examples you provide. Do you have any idea what is causing this?
Are those files necessary only for the examples or are they needed for using `RERconverge` in production?

**Comment by wgmao** [comment]
If you want to recover what are under /data in the repo, you can follow the steps below.
```
setwd("path_to_your_R_library/RERconverge/data/")
#you can see data contained in the file
readRDS("Rdata.rds") 
lazyLoad(filebase = "Rdata", envir = parent.frame())
#load mamTrees as an example
find(mamTrees)
```

**Comment by vanzod** [comment]
@sorrywm Thank you for the clarification. We installed `RERconverge` from the sources in your release archive. We cannot do a `install_install` since we need to keep track of versioning in our software stack.
The user that spotted this issue was trying to replicate the steps you provide in [1] and it was failing at
```
load(paste(rerpath,'/data/logAdultWeightcm.RData',sep=''))
```
since the file does not exists.
However if such files are not required for using `RERconverge` from now on we will instruct our users to download them directly from the GitHub repository.

[1] https://www.csb.pitt.edu/faculty/clark/files/RERconvergeAnalysisFullWalkthrough.html

**Comment by sorrywm** [comment]
@vanzod There is an updated version of our walk-through that loads the data without reference to that directory at [](https://cdn.rawgit.com/nclark-lab/RERconverge/master/vignettes/RERconvergeAnalysisFullWalkthrough.html). Did you navigate to the walk-through from the Clark lab website? We will update that and make sure any references to it are updated as well. Here is the way we load the data in the new vignette:
data("logAdultWeightcm")
Please let us know if you encounter any other bugs/errors in the new vignette.

**Comment by vanzod** [comment]
@sorrywm Thank you. I will forward your suggestion to our user and I will let you know.

**Comment by nclark-lab** [comment]
@vanzod Thank you for bringing this to our attention. I hope the new walk-through resolves the issue. Please let us know if the user was able to use RERconverge.

**Comment by vanzod** [comment]
@nclark-lab I have not heard back from the user in quite some time. I presume everything is working fine now. Thank you for your prompt feedback.

**Comment by nclark-lab** [comment]
You're welcome.
