### ISSUE TITLE
Does the paralog genes from the same gene tree affect the output?

### ISSUE THREAD

**Issue by hongzhonglu** [nclark-lab/RERconverge#51]
Hi, could I ask a question? In my analysis, I found for some ortholog gene groups, the paralog genes existed for some species, does it affect the evolution rate analysis?

**Comment by nclark-lab** [comment]
This is an important question. It is important to stringently filter out paralogous sequences from the alignments to the best that is possible. They have been seen to diminish signals in important correlations. They could also potentially create false positive correlations.  Some potential methods to identify strictly orthologous groups are InParanoid and whole genome alignments that use synteny (blastz chain alignments).
Best of luck with your analysis!

**Comment by hongzhonglu** [comment]
@nclark-lab Great thanks for your help!
