### ISSUE TITLE
Issues installing RERconverge on R 4.0 (Mac OS Catalina 10.15.5)

### ISSUE THREAD

**Issue by kjf319** [nclark-lab/RERconverge#55]
Unable to install RERconverge on R 4.0.2. Using on a Mac OS Catalina 10.15.5. Attempted to bypass error through process listed in comments error report #52. I installed dependencies for devtools, installed Xcode , slang6 and gfortran, created a .bash_profile in home directory and added '''export PATH=/usr/local/clang6/bin:$PATH''' and then reinstalled from GitHub in Rstudio. I also tried using R console and reinstalling as opposed to Rstudio. I received the same error message as before-

'''ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [RERconverge.so] Error 1
ERROR: compilation failed for package ‘RERconverge’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RERconverge’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RERconverge’
Error: Failed to install 'RERconverge' from GitHub:
  (converted from warning) installation of package ‘/var/folders/7t/ccwgf8xs0w97qz2g0g0tnc080000gn/T//RtmpezuDfu/file52e338409d/RERconverge_0.1.0.tar.gz’ had non-zero exit status'''

**Comment by wgmao** [comment]
Thank you for your feedback. I have tried the following solutions on Catalina 10.15 & R 4.0.2. and both of these two solutions work for me.

### Solution 1
Could you try the following steps:
1) delete the `.bashrc_profile`
2) Try install `RERconverge` from the R console
```
library(devtools)
install_github("nclark-lab/RERconverge")
```

### Solution 2
If the first solution doesn't work, could you try this pre-compiled binary installation?
[RERconverge_0.1.0.tgz.zip](https://github.com/nclark-lab/RERconverge/files/5106710/RERconverge_0.1.0.tgz.zip)
1) Unzip the file to get `RERconverge_0.1.0.tgz`
2) `R CMD INSTALL RERconverge_0.1.0.tgz`

**Comment by kjf319** [comment]
Hi @wgmao,

Thank you for the potential solutions. I tried solution one, but deleted the bash profile (.bash_profile) with recommended edits in issue #52. There was no .bashrc_profile. When I tried this, installation failed with the following error message : /usr/local/clang8/bin/clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/ape/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:26:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
In file included from /usr/local/clang8/bin/../include/c++/v1/cmath:305:
/usr/local/clang8/bin/../include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘RERconverge’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RERconverge’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RERconverge’
Error: Failed to install 'RERconverge' from GitHub:
  (converted from warning) installation of package ‘/var/folders/7t/ccwgf8xs0w97qz2g0g0tnc080000gn/T//Rtmpnjs1tp/file8672372e252/RERconverge_0.1.0.tar.gz’ had non-zero exit status


I also tried solution 2. The unzipped file downloaded from your link (https://github.com/nclark-lab/RERconverge/files/5106710/RERconverge_0.1.0.tgz.zip) was named RERconverge.0.1.0.tar. After downloading and unzipping, I tried to install RERconverge using the code you provided. The install appeared to work, as I got the following message: * installing to library ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’
* installing *binary* package ‘RERconverge’ ...
* DONE (RERconverge)

When I went to look at the library in R library(RERconverge), I got the following error message :
 Error: package or namespace load failed for ‘RERconverge’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RERconverge/libs/RERconverge.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RERconverge/libs/RERconverge.so, 6): Library not loaded: /usr/local/gfortran/lib/libgfortran.3.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RERconverge/libs/RERconverge.so
  Reason: image not found

Let me know something I could check in differences in my environment and what you're using. Thanks!

**Comment by kjf319** [comment]
Hi @wgmao,

I successfully installed RERconverge through instructions on https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/ and then installing through GitHub (as recommended on the installation page) on the R console (not R Studio). It might be worth updating the install page for RERconverge with these instructions, as the current instructions didn't work well with macOS Catalina 10.15.5.

Thanks!

**Comment by wgmao** [comment]
Thank you for directing us to this great resource. This also works for Big Sur which is awesome. Many thanks.
