### ISSUE TITLE
Output of fastwilcoxGMTAll

### ISSUE THREAD

**Issue by evolgen** [nclark-lab/RERconverge#56]
Dear developers,

I am trying to understand the output of the enrichment test using fastwilcoxGMTAll.
What does the stat in the output represent - is it the enrichment score or the test statistic. Since the values are negative, I am assuming these do not represent the AUC scores.
I couldn't find additional info in the manual or walkthrough, could you please clarify this?

Thank you for your time.

Best,
Rohit

**Comment by Amylith** [comment]
Hi Rohit!  The statistic output is an approximation of the AUC-0.5, which is where the negative values come from.  Therefore a value of (positive) 0.5 is the strongest positive enrichment (acceleration in foreground species) and a value of -0.5 is the strongest negative enrichment (deceleration in foreground species).
