### ISSUE TITLE
Cannot Install RERconverge

### ISSUE THREAD

**Issue by amgraham07** [nclark-lab/RERconverge#67]
I had previously installed RERconverge, however I recently needed to uninstall then reinstall R + Rstudio. I was able to install and load all my previous packages without issue, however I am unable to install RERconverge again.

I am using...
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)
AND
"Prairie Trillium" Release (9f796939, 2022-02-16) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

I've tried it 3 different ways, none of which work...

>remotes::install_github("nclark-lab/RERconverge")
>install_github("nclark-lab/RERconverge", force = TRUE)
>devtools::install_github("nclark-lab/RERconverge")

I've included the readout from all three ways as an attachment.
[RERconverge_errors.txt](https://github.com/nclark-lab/RERconverge/files/8226927/RERconverge_errors.txt)

**Comment by wgmao** [comment]
First, could you type `gcc --version` and `gfortran --version` in the terminal to check if they are both properly installed? 
If these tools have been properly installed, could you try to install in the terminal instead of rstudio?

**Comment by amgraham07** [comment]
For gcc --version...
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

For gfortran --version...
GNU Fortran (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.

When I do it in the terminal window, it stills says it fails.
[RERconverge_errors_2.txt](https://github.com/nclark-lab/RERconverge/files/8228194/RERconverge_errors_2.txt)

**Comment by amgraham07** [comment]
I accidentally "closed" the issue, but it is still an ongoing problem.

**Comment by amgraham07** [comment]
I was able to switch from gcc to clang in my R makefile, and that seems to have allowed it to install and be loaded into my workspace.

**Comment by wgmao** [comment]
Glad to hear the problem has been resolved! Could you elaborate the changes you made in the makefile if it is not too much effort? I am going to include in the `Install FAQ` for other users with similar problems.

**Comment by amgraham07** [comment]
Sure! I've included how I changed my makefile to allow me to switch back and forth between gcc and clang, if errors related to compilers arise. This was something another R user suggested for a different set of programs, but I found that it worked for me in this case...

CFLAGS +=             -O3 -Wall -pipe -pedantic -std=gnu99
CXXFLAGS +=           -O3 -Wall -pipe -Wno-unused -pedantic 
#VER=-4.6
#VER=-4.7
VER=-4.8.5
#CC=ccache gcc$(VER)
#CXX=ccache g++$(VER)
SHLIB_CXXLD=g++$(VER)
FC=ccache gfortran
F77=ccache gfortran
MAKE=make -j8
CXX=clang++
CC=clang

**Comment by wgmao** [comment]
Thanks! I have included this in the `Install FAQ`.
