### ISSUE TITLE
Different rho and p-values for the same gene in the table and figure

### ISSUE THREAD

**Issue by pkfsantos** [nclark-lab/RERconverge#70]
Hello All,
I wonder if other people have the same output discrepancy between the table and the figure.
These are some examples:

Correlation output table:
GeneX - Rho=0.5086805, N=90, P=3.072072e-07, p.adj=0.0006248594
Figure:
GeneX - rho= 0.4077, p=0

Correlation output table:
GeneY - Rho=-0.3560498, N=81, P=1.105311e-03, p.adj=0.0446318243
Figure:
GeneY - rho=-0.305, p=5e-04

I wonder why there is this difference. I would expect to be the same values in the table and the figure.

Sincerely,
Priscila

**Comment by nclark-lab** [comment]
Hi Priscilla,
Could you give us more details? Such as which figures you’re referring to? And perhaps the code you ran to get these values.
Best,
-Nathan Clark


On Sep 2, 2022, at 1:24 PM, pkfsantos ***@***.******@***.***>> wrote:



Hello All,
I wonder if other people have the same output discrepancy between the table and the figure.
These are some examples:

Correlation output table:
GeneX - Rho=0.5086805, N=90, P=3.072072e-07, p.adj=0.0006248594
Figure:
GeneX - rho= 0.4077, p=0

Correlation output table:
GeneY - Rho=-0.3560498, N=81, P=1.105311e-03, p.adj=0.0446318243
Figure:
GeneY - rho=-0.305, p=5e-04

I wonder why there is this difference. I would expect to be the same values in the table and the figure.

Sincerely,
Priscila

**Comment by pkfsantos** [comment]
Hi Nathan,

Yes, sure.
This was the code:

```
estimatePhangornTreeAll(alndir ="alignments_folder/", pattern = ".fa",
                                      treefile = "SpeciesTree_rooted.txt", 
                                      output.file = "input_same_topology.txt ", submodel = "LG",
                                      type = "AA", format = "fasta", k = 4)

ort_trees1 <- readTrees("input_same_topology.txt", reestimateBranches = F, minSpecs = 14)
```
Read 4678 items
max is 14
Rotating trees
estimating master tree branch lengths from 4678 genes
Naming columns of paths matrix

```
mamRERw = getAllResiduals(ort_trees1, transform = "sqrt", weighted = T, scale = T)
```
cutoff is set to 0.00331200468385
collapsing to unique 'x' values

```
noDevDiap <-c(“Frieseomelitta_varia”,”Lasioglossum_albipes","Lasioglossum_leucozonium","Augochlora_pura","Augochlorella_aurata","Apis_mellifera","Bombus_terrestris","Ceratina_calcarata”)

noDevDiapb2a <- foreground2Tree(noDevDiap, ort_trees1, clade="all", weighted = T, transition = "unidirectional")

phenVnoDevDiap <- tree2Paths(noDevDiapb2a,ort_trees1)

cornoDevDiap <- correlateWithBinaryPhenotype(mamRERw, phenVnoDevDiap, weighted = T)**

head(cornoDevDiap[order(cornoDevDiap$P),], n = 4)
```
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

  | Rho<dbl> | N<dbl> | P<dbl> | p.adj<dbl>
-- | -- | -- | -- | --
OG0002726 | 0.7556866 | 25 | 1.254001e-05 | 0.05730786
OG0006439 | -0.7068286 | 25 | 7.818013e-05 | 0.13208220
OG0005972 | 0.7468914 | 21 | 1.003120e-04 | 0.13208220
OG0003697 | 0.7145508 | 23 | 1.278281e-04 | 0.13208220

</html>

```
par(mfrow=c(1,1))
plotRers(mamRERw,"OG0003697",phenv=phenVnoDevDiap)
```
<img width="781" alt="Screen Shot 2022-09-07 at 1 43 08 PM" src="https://user-images.githubusercontent.com/27377470/188964450-314d3184-8afc-4f2e-8d02-1db0e84fdf28.png">

For example, for the gene OG0003697, the output table says Rho = 0.71 vs Figure rho = 0.6140, P = 1.27 e-04 (table), p = 3e-04 (Figure). Why is there a difference between the table and the figure outputs? I get different values for all genes.

I have another question. 
I run a similar script for more species (61 in total). One of the differences was in the "foreground2Tree(noDevDiap, ort_trees1, clade="all", weighted = T, transition = "unidirectional")" that I used clade = "terminal" and transition = "bidirectional".  In this new analysis, not all species appear on the estimated RERs plot (for some genes). I used trees with all species included, so why sometimes do not all species appear on the plot?

Best,
Priscila

**Comment by pkfsantos** [comment]
Hi Nathan,

So, I realized I get different numbers between the table and the figure when I run the foreground2Tree with weighted = T. But I still don't understand why that happens.

Best,
Priscila

**Comment by sorrywm** [comment]
Hi Priscilla,

At the moment the default in `plotRers` is to report the Rho and p-values based on default settings for `getAllCor`, one of which is `weighted = F`. You can check this by re-running the analyses with `weighted = F` when generating the phenotype tree, and you should get the same Rho and p as reported in the plot label. This should not change the plot itself, however; the RER values themselves come from `mamRERw`, which you have already computed.

One thing that might be confusing here is that there are two different types of **weighting** in your analysis. 

1. In computing the RERs using `getAllResiduals`, `weighted = T` means that you are using a weighted regression to compute relative rates where branch lengths affect weights. This is recommended to reduce the effects of heteroscedasticity (where the mean and variance of branch lengths are correlated); for more details see [Partha, Kowalczyk, Clark, and Chikina (2019)](https://academic.oup.com/mbe/article/36/8/1817/5488195). 
2. In generating the phenotype tree from the foreground species using `foreground2Tree`, `weighted = T` means that you are distributing the foreground phenotype across branches within a clade. You can visualize these weights by labeling your branches using something like:
`plot(noDevDiapb2a, use.edge.length=F)`
`edgelabels(noDevDiapb2a$edge.length)` #see more options for this function if needed for aesthetics

I believe that to recapitulate the default for `plotRers` you would need to use `weighted = F` in both `foreground2Tree` and `correlateWithBinaryPhenotype` (but not `getAllResiduals`). The latest version of RERconverge might also treat a weighted phenotype tree as categorical when plotting RERs, which would give you different colored points for each unique edge length. 

All this is to say: If you want to examine your Rho and p-values, use the results you have obtained from `correlateWithBinaryPhenotype`, not what shows up when you run `plotRers`. Even if the Rho and p are not right, the plotted RERs should be, so you can still use the `plotRers` function to visualize RERs across lineages in your analyses.

Thank you for using RERconverge!

Sincerely,
Wynn

**Comment by pkfsantos** [comment]
Hi Wynn,
Thank you very much for the explanation. I really appreciate it.
Best,
Priscila

**Comment by nclark-lab** [comment]
Hello,

Thanks for sending the code. I’m working on defining the source of the problem now. Would you mind sending the file “input_same_topology.txt”.  If you’d rather not, then I’ll try to replicate it on another dataset.

Best,
-Nathan



On Sep 7, 2022, at 2:08 PM, pkfsantos ***@***.******@***.***>> wrote:



Hi Nathan,

Yes, sure.
This was the code:

estimatePhangornTreeAll(alndir ="alignments_folder/", pattern = ".fa",
                                      treefile = "SpeciesTree_rooted.txt",
                                      output.file = "input_same_topology.txt ", submodel = "LG",
                                      type = "AA", format = "fasta", k = 4)

ort_trees1 <- readTrees("input_same_topology.txt", reestimateBranches = F, minSpecs = 14)


Read 4678 items
max is 14
Rotating trees
estimating master tree branch lengths from 4678 genes
Naming columns of paths matrix

mamRERw = getAllResiduals(ort_trees1, transform = "sqrt", weighted = T, scale = T)


cutoff is set to 0.00331200468385
collapsing to unique 'x' values

noDevDiap <-c(“Frieseomelitta_varia”,”Lasioglossum_albipes","Lasioglossum_leucozonium","Augochlora_pura","Augochlorella_aurata","Apis_mellifera","Bombus_terrestris","Ceratina_calcarata”)

noDevDiapb2a <- foreground2Tree(noDevDiap, ort_trees1, clade="all", weighted = T, transition = "unidirectional")

phenVnoDevDiap <- tree2Paths(noDevDiapb2a,ort_trees1)

cornoDevDiap <- correlateWithBinaryPhenotype(mamRERw, phenVnoDevDiap, weighted = T)**

head(cornoDevDiap[order(cornoDevDiap$P),], n = 4)


        Rho     N       P       p.adj
OG0002726       0.7556866       25      1.254001e-05    0.05730786
OG0006439       -0.7068286      25      7.818013e-05    0.13208220
OG0005972       0.7468914       21      1.003120e-04    0.13208220
OG0003697       0.7145508       23      1.278281e-04    0.13208220

par(mfrow=c(1,1))
plotRers(mamRERw,"OG0003697",phenv=phenVnoDevDiap)


[Screen Shot 2022-09-07 at 1 43 08 PM]<https://user-images.githubusercontent.com/27377470/188964450-314d3184-8afc-4f2e-8d02-1db0e84fdf28.png>

For example, for the gene OG0003697, the output table says Rho = 0.71 vs Figure rho = 0.6140, P = 1.27 e-04 (table), p = 3e-04 (Figure). Why is there a difference between the table and the figure outputs? I get different values for all genes.

I have another question.
I run a similar script for more species (61 in total). One of the differences was in the "foreground2Tree(noDevDiap, ort_trees1, clade="all", weighted = T, transition = "unidirectional")" that I used clade = "terminal" and transition = "bidirectional". In this new analysis, not all species appear on the estimated RERs plot (for some genes). I used trees with all species included, so why sometimes do not all species appear on the plot?

Best,
Priscila
