### ISSUE TITLE
Number of input species and explanation of output

### ISSUE THREAD

**Issue by zhxh233** [nclark-lab/RERconverge#88]
Hi!

Thank you for developing this useful tool! While reading the tutorial, I thought of two questions, Could you please enlighten me?

1. In other issues, you suggested that there shouldn't be too few genes as it would affect the normalization. I'm curious if the number of species has any impact, for example, 5, compared to the default setting of 10?
2. In tutorial, you've mentioned that further analyses could be done like using branch-site models to determine if fast-evolving genes are experiencing relaxation of constraint or undergoing directional selection, does this mean that **ideally**, all (or at least the vast majority of) genes which are experiencing relaxation of constraint would exhibit a high evolutionary rate?

Any information would be super helpful, thanks!

**Comment by zhxh233** [comment]
Besides, if the topology of gene is not like species and we force it to be (using estimatePhangornTreeAll), does it mean that it will affect the mutation rate on some branches, and this is also the basis for statistical testing based on the mutation rate later ?

**Comment by nclark-lab** [comment]
Thanks for your interest. For question 1, when there are too few species for a given gene, there can be a lack of power to identify genes with convergent rate shifts. With as few as 5 species, there could be some information if there are strong contrasts in the trait between the species involved.
For question 2, Yes, genes which have experienced a sustained relaxation of constraint will have accelerated evolutionary rates. In fact, relaxation is easier to detect than cases of episodic positive selection.

**Comment by nclark-lab** [comment]
You're welcome. Good luck with your project.
